/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package online.prostobank.clients.api.dto.avro.dbo;
@org.apache.avro.specific.AvroGenerated
public enum AccountStatus implements org.apache.avro.generic.GenericEnumSymbol<AccountStatus> {
  reservation, closure, wait_for_docs, open  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AccountStatus\",\"namespace\":\"online.prostobank.clients.api.dto.avro.dbo\",\"symbols\":[\"reservation\",\"closure\",\"wait_for_docs\",\"open\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
