/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package online.prostobank.clients.api.dto.avro.dbo;

@org.apache.avro.specific.AvroGenerated
public interface Api {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Api\",\"namespace\":\"online.prostobank.clients.api.dto.avro.dbo\",\"types\":[{\"type\":\"record\",\"name\":\"ChangeAccountStatus\",\"fields\":[{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"inn\",\"type\":\"string\"},{\"name\":\"timeEvent\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"}},{\"name\":\"accountNumber\",\"type\":\"string\"},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"AccountStatus\",\"symbols\":[\"reservation\",\"closure\",\"wait_for_docs\",\"open\"]}}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends Api {
    public static final org.apache.avro.Protocol PROTOCOL = online.prostobank.clients.api.dto.avro.dbo.Api.PROTOCOL;
  }
}