LOG_PATH: /opt/crm/logs
abs:
    client-code: dfdhftre
    client-id: 152249
    client-source: PROSTO
    status-check:
        cron: 0 0/5 * * * *
    url: https://h2h.creditural.ru:7443/api/1.0
    partner_id: 152249
    partner_user: 152249
    partner_pass: dfdhftre
account:
    application:
        table:
            view:
                title: 'CRM | Просто Банк'
app:
    email-back: ''
    email-debug: ''
    email-delivery: t.usupbaev@apibank.club
    email-front: ''
    email-sender-name: notify@prostobank.online
    lk:
        url: https://stage-0.apibank.club/account/application/
    p550:
        fake: false
    url: https://stage-0.apibank.club/crm/applications/
    base-url: https://stage-0.apibank.club/crm/
    tss-url: https://stage-0.apibank.club/tss/
artemis:
    broker-url: tcp://localhost:61618
    login: test
    password: test
bigdata:
    kyc:
        auth-url: http://192.168.70.34:8084/auth/v5.9/authenticate-by-pass
        base-url: http://192.168.70.34:8084/api
        'on': 1
cache:
    users:
        timeout: 180000
dbo:
    enable: true
    host: https://stage-0.apibank.club
    apiUrl: /dbo-api
    usersUrl: /users
    queue:
        enabled: false
    checkOld:
        enabled: true
        cron: 0 0/10 * ? * *
dboLink:
    url: https://lk.prostobank.online/
dev:
    confiramtion:
        code: 1233
        code.switch: 1
egrul:
    file:
        parser:
            service:
                address: http://127.0.0.1:9000/parser/api.php
emarsys:
    api:
        key: hyNQtKMVBTZCPyggqvqd
        url: https://api.emarsys.net/api
        user: apibank002
expiredpassports:
    cron: 0 0 3 ? * *
    enabled: true
    httpsurl: https://guvm.mvd.ru/upload/expired-passports/list_of_expired_passports.csv.bz2
fns:
    db: jdbc:postgresql://10.193.20.24:5432/egr
    password: KGFori3wer
    username: egrreader
ftp:
    baseUrl: http://data.nalog.ru/opendata/7707329152-sshr/
    host: 192.168.70.38
    password: ftp-user
    port: 21
    userName: ftp-user
google:
    analytics:
        event:
            category: crm
        id: UA-123670260-1
        type: event
        url: http://www.google-analytics.com/collect
        version: 1
inbound-mail:
    enabled: false
    failed-folder: TEST-FAIL
    fixedDelay: 20000
    maxMessagesPerPoll: 3
    success-folder: done
    timeout: 10000
    url: imaps://client-docs-stage:ahReezahy7@mail.apibank.online/INBOX
ipwhois:
    enabled: true
is:
    utm:
        active: 1

keycloak:
    enabled: true
    auth-server-url: https://stage-0.apibank.club/auth
    realm: ProstoBank
    resource: telemarket
    credentials:
        secret: a027f2c0-564c-47a3-a230-803639cddcc0
    ssl-required: external
    principal-attribute: preferred_username


kontur:
    allowed:
        till:
            val: 1.0
    api-key: 56ed04b3-6e3c-4ab5-97b5-b217de57603c
    auth-login: a.chernikov@gpbdigital.com
    auth-password: apiBank2018
    auth-url: https://api.kontur.ru/auth/v5.11/authenticate-by-pass
    base-url: https://kyc.kontur.ru/api
    company:
        info:
            base-url: https://focus-api.kontur.ru/api3
    retreive:
        info:
            'on': 0
logging:
    level:
        org:
            springframework:
                integration:
                    mail:
                        ImapMailReceiver: WARN
#            keycloak: DEBUG
        online:
            prostobank:
                clients: INFO

management:
    endpoint:
        health:
            show-details: always
server:
    connection-timeout: 300000
    port: 38081
    servlet:
        contextPath: /crm
simple:
    branch: 1
    crypto-id: 370750
    host: bank.test.apibank.club
    imsi:
        check:
            period:
                of:
                    time: 1800000
        notification:
            users: a.chernikov@apibank.club,ulyana.emelyanova@creditural.ru
    jdbc-driver-class-name: org.postgresql.Driver
    jdbc-password: isimplelab
    jdbc-url: jdbc:postgresql://bank.test.apibank.club:5432/isimplelab
    jdbc-username: isimplelab
    login: oper
    password: oper
    prosto-crypto-id: 370750
    prosto-group-name: Просто
    url: http://bank.test.apibank.club
sms:
    attempts:
        max: 5
    blacklisted: 9262499598
    login: gpbdigi3
    partner: Prostobank
    password: Q5ePWSE8
    time:
        gap: 60
    uri: http://gate10.mfms.ru:12105/gpbdigital/connector3/service/
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        password: smebank
        url: jdbc:postgresql://localhost:5432/smebank
        username: smebank
    jpa:
        properties:
            hibernate:
                default_schema: public
                dialect: org.hibernate.dialect.PostgreSQL95Dialect
                jdbc:
                    lob:
                        non_contextual_creation: true
    mail:
        host: mail.apibank.online
        port: 587
        username: apibank.local/notify
        password: V1x4i@ZAmQDy2HLx
        properties:
            mail:
                smtp:
                    starttls:
                        enable: true
    main:
        allow-bean-definition-overriding: true
    servlet:
        multipart:
            max-file-size: 20MB
statistic:
    api:
        have: +
        none: '-'
storage:
    url: http://192.168.70.15/contentstorage
    host: stage-0.apibank.club
token:
    encryptor:
        seed: 4818ca36-aac1-4129-95b2-5fbda765a5be

statemachine:
    clear_context: 0 0 */1 * * *
toggle:
    features:
        -
            name: ai_predict
            enabled: true

ai:
    url-init-scoring: http://192.168.70.15:8093/crm_ai/init_train
    url-get-result: http://192.168.70.15:8093/crm_ai/predict_proba
    scheduler: 0 0 0/1 * * ?
    page-size: 1
