analytics:
    production: false

app:
    email-sender-class: online.prostobank.clients.connectors.email.SmtpEmailConnector
    sms-sender-class: online.prostobank.clients.connectors.sms.MfmsSender

cache:
    users:
        timeout: 180000

#
#keycloak:
#    securityConstraints:
#    -   authRoles:
#        - '*'
#        securityCollections:
#        -   name: for auth users
#            patterns:
#            - /api/account_application/*
#    -   authRoles:
#        - '*'
#        securityCollections:
#        -   name: for auth users
#            patterns:
#            - /api/attachment/*
#    -   authRoles:
#        - '*'
#        securityCollections:
#        -   name: for auth users
#            patterns:
#            - /api/stats/*
#    -   authRoles:
#        - '*'
#        securityCollections:
#        -   name: for auth users
#            patterns:
#            - /api/client_attachment/*
#    -   authRoles:
#        - '*'
#        securityCollections:
#        -   name: for auth users
#            patterns:
#            - /api/client/*
#    -   authRoles:
#        - '*'
#        securityCollections:
#        -   name: for auth users
#            patterns:
#            - /api/dictionary/*
#    -   securityCollections:
#        -   name: for all
#            patterns:
#            - /api/*
#    -   authRoles:
#        - '*'
#        securityCollections:
#        -   name: for auth users
#            patterns:
#            - /*

### Конфигурация внутренней безопасности ###
#security:
#    prop:
#        # Иерархия ролевой модели
#        role-hierarchy:
#            ROLE_ADMIN: ROLE_USER_ADMIN, ROLE_ORDER_ADMIN
#
#        # список внутренних прав
#        permissions:
#            ROLE_ORDER_ADMIN: ['bank-manager', 'offline_access', 'pos-admin', 'pos-access', 'uma_authorization', 'pos-back', 'pos-front', 'operator']
#            ROLE_ORDER_DISPATCHER: ['bank-manager', 'offline_access']


kontur:
    allowed:
        till:
            val: 1.0


logging:
    level:
        club:
            apibank:
                connectors:
                    analytics: DEBUG


smartengines:
    trial: true
spring:
    artemis:
        embedded:
            queues: sms,email,sysemail,keycloak
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                create_empty_composites:
                    enabled: true
    profiles:
        active: '@activatedProperties@'
