abs:
    client-code: dfdhftre
    client-id: 152249
    client-source: PROSTO
    status-check:
        cron: 0 0/5 * * * *
    url: https://h2h.creditural.ru:7443/api/1.0
    partner_id: 152249
    partner_user: 152249
    partner_pass: dfdhftre
account:
    application:
        table:
            view:
                title: CRM | Просто Банк
app:
    email-back: ''
    email-debug: ''
    email-delivery: ''
    email-front: ''
    email-sender-name: notify@prostobank.online
    lk:
        url: http://localhost:8080/account/application/
    url: http://localhost:8080/crm/applications/
    base-url: http://localhost:8080/crm/
    tss-url: https://stage-0.apibank.club/tss/
artemis:
    broker-url: tcp://localhost:61616
    login: test
    password: test
bigdata:
    kyc:
        auth-url: http://192.168.70.15:8084/auth/v5.9/authenticate-by-pass
        base-url: http://192.168.70.15:8084/api
        'on': 1
cache:
    users:
        timeout: 600
dbo:
    enable: true
    host: https://stage-0.apibank.club
    apiUrl: /dbo-api
    usersUrl: /users
    queue:
        enabled: false
    checkOld:
        enabled: false
        cron: 0 0 */1 ? * *

dboLink:
    url: https://lk.prostobank.online/
dev:
    confiramtion:
        code: 1233
        code.switch: 1
egrul:
    file:
        parser:
            service:
                address: http://127.0.0.1:8081/api.php
emarsys:
    api:
        key: hyNQtKMVBTZCPyggqvqd
        url: https://api.emarsys.net/api
        user: apibank002
expiredpassports:
    cron: 0 0 3 ? * *
    enabled: true
    httpsurl: https://guvm.mvd.ru/upload/expired-passports/list_of_expired_passports.csv.bz2
fns:
    db: jdbc:postgresql://192.168.70.5:5432/egr
    password: KGFori3wer
    username: egrreader
ftp:
    baseUrl: http://data.nalog.ru/opendata/7707329152-sshr/
    host: 192.168.70.38
    password: ftp-user
    port: 21
    userName: ftp-user
google:
    analytics:
        event:
            category: crm
        id: UA-123670260-1
        type: event
        url: http://www.google-analytics.com/collect
        version: 1
inbound-mail:
    enabled: false
    failed-folder: TEST-FAIL
    fixedDelay: 1000
    maxMessagesPerPoll: 3
    success-folder: done
    timeout: 10000
    url: imaps://client-docs-stage:ahReezahy7@mail.apibank.online/INBOX
ipwhois:
    enabled: true
is:
    utm:
        active: 0

### Конфигурация Keycloak ###
keycloak:
    # enable the Keycloak Spring Boot Adapter
    enabled: true
    auth-server-url: https://stage-0.apibank.club/auth
    realm: ProstoBank
    resource: telemarket
    credentials:
        secret: a027f2c0-564c-47a3-a230-803639cddcc0
    ssl-required: external
    principal-attribute: preferred_username

#    enable-basic-auth: true
#    use-resource-role-mappings: true
#    token-minimum-time-to-live: 30


kontur:
    allowed:
        till:
            val: 1.0
    api-key: 56ed04b3-6e3c-4ab5-97b5-b217de57603c
    auth-login: a.chernikov@gpbdigital.com
    auth-password: apiBank2018
    auth-url: https://api.kontur.ru/auth/v5.11/authenticate-by-pass
    base-url: https://kyc.kontur.ru/api
    company:
        info:
            base-url: https://focus-api.kontur.ru/api3
    retreive:
        info:
            'on': 1
logging:
    level:
        club:
            apibank:
                connectors:
                    analytics: DEBUG
                    kontur:
                        KonturKycService: DEBUG
        online:
            prostobank:
                clients:
                    ROOT: DEBUG
                    LoggingRequestInterceptor: DEBUG
                    services:
                        attacment:
                            aux_migration:
                                AttachmentExportService: DEBUG
        org:
            hibernate:
                SQL: ERROR
                type:
                    descriptor:
                        sql:
                            BasicBinder: ERROR
            springframework:
                integration:
                    mail:
                        ImapMailReceiver: WARN
#            keycloak: DEBUG

management:
    endpoint:
        health:
            show-details: always
server:
    servlet:
        session:
            timeout: 120
        contextPath: /crm
simple:
    branch: 1
    host: bank.test.apibank.club
    imsi:
        check:
            period:
                of:
                    time: 999999999
        notification:
            users: i.hudyakov@apibank.club
    jdbc-driver-class-name: org.postgresql.Driver
    jdbc-password: isimplelab
    jdbc-url: jdbc:postgresql://bank.test.apibank.club:5432/isimplelab
    jdbc-username: isimplelab
    login: oper
    password: oper
    url: http://bank.test.apibank.club
sms:
    attempts:
        max: 5
    blacklisted: 9262499598
    login: gpbdigi3
    partner: Prostobank
    password: Q5ePWSE8
    time:
        gap: 60
    uri: http://gate10.mfms.ru:12105/gpbdigital/connector3/service/
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        initialization-mode: always
        password: pospass
        url: jdbc:postgresql://localhost:5433/pos
        username: posuser
    jpa:
#        hibernate:
#            ddl-auto: create
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        properties:
            hibernate:
                default_schema: public
                temp:
                    use_jdbc_metadata_defaults: false
        show-sql: false
    mail:
        host: mail.apibank.online
        port: 587
        username: apibank.local/notify
        password: V1x4i@ZAmQDy2HLx
        properties:
            mail:
                smtp:
                    starttls:
                        enable: true
    main:
        allow-bean-definition-overriding: true
    servlet:
        multipart:
            max-file-size: 20MB
statistic:
    api:
        have: +
        none: '-'
storage:
    url: http://192.168.70.15/contentstorage
    host: stage-0.apibank.club
token:
    encryptor:
        seed: 4818ca36-aac1-4129-95b2-5fbda765a5be

aspect:
    benchmark: false
    exception: false
    logger: false
    validation: false
statemachine:
    clear_context: 0 0 */1 * * *

toggle:
    features:
        -
          name: ai_predict
          enabled: true

ai:
    url-init-scoring: http://192.168.70.15:8093/crm_ai/init_train
    url-get-result: http://192.168.70.15:8093/crm_ai/predict_proba
    scheduler: 0 0 0/1 * * ?
    page-size: 1
